const connectSrc = [
  '\'self\''
  'blob:'
  '14257-chimera.adobeioruntime.net'
  '*.adobe.com'
  '*.clicktale.net/'
  '*.adobe.io'
  '*.adobelogin.com'
  '*.amazonaws.com'
  '*.blob.core.windows.net'
  '*.mktoresp.com'
  'accounts.google.com/gsi/log'
  'accounts.google.com/gsi/status'
  'acom-reviews--adobe.hlx.live/reviews-api/'
  'ade0164.d41.co/'
  'adobe.tt.omtrdc.net'
  'adobedc.demdex.net/'
  'adobeioruntime.net'
  'adobesearch.adobe.io'
  'analytics.tiktok.com'
  'api.company-target.com/api/v2/'
  'api.iperceptions.com'
  'bat.bing.com/'
  'c.go-mpulse.net'
  'cdn.cookielaw.org'
  'dc-api.adobe.io'
  'dpm.demdex.net/'
  'geolocation.onetrust.com/'
  'lasteventf-tm.everesttech.net'
  'p13n.adobe.io/'
  'pdfnow.adobe.io'
  'privacyportal.onetrust.com'
  'tr.snapchat.com/'
  'main--dc--adobecom.hlx.page'
  'main--milo--adobecom.hlx.page'
  'main--dc--adobecom.hlx.live'
  'cdn.linkedin.oribi.io'
  '*.typekit.net/'
  'trial-eum-clienttons-s.akamaihd.net/'
  '*.akstat.io/'
  '345-tti-184.mktoutil.com'
  'adservice.google.com'
  'rum.hlx.page'
  'us-central1-adaptive-growth.cloudfunctions.net'
  'ad.doubleclick.net'
  'cdnmd.global-cache.online'
  'ff.kis.v2.scr.kaspersky-labs.com'
  'gc.kes.v2.scr.kaspersky-labs.com'
  'gc.kis.v2.scr.kaspersky-labs.com'
  'me.kis.v2.scr.kaspersky-labs.com'
  'pagead2.googlesyndication.com'
  'tag-logger.demandbase.com'
  'tl.ytlogs.ru'
  'tr.snapchat.com'
  'trial-eum-clienttons-s.akamaihd.net'
  'www.google.com'
  ';'',
];

const defaultSrc = [
  '\'self\'',
  'acrobat.adobe.com',
  'auth.services.adobe.com',
  'documentcloud.adobe.com',
  'acrobat.adobe.com',
  ';',
];

const fontSrc = [
  '\'self\''
  'use.typekit.net'
  'assets.merci-app.com'
  'fonts.bunny.net'
  'fonts.gstatic.com'
  ';'',
];

const formAction = [
  '*.adobelogin.com',
  '*.snapchat.com/',
  'helpx.adobe.com',
  'www.adobe.com',
  'www.facebook.com/tr/',
  ';',
];

const frameSrc = [
  '\'self\''
  'data:'
  'blob:'
  '*.amazonaws.com'
  '*.blob.core.windows.net'
  '9212252.fls.doubleclick.net'
  'accounts.google.com'
  'acrobat.adobe.com'
  'adobe.demdex.net'
  'bid.g.doubleclick.net'
  'dc-api.adobecontent.io'
  'documentcloud.adobe.com'
  'servedby.flashtalking.com'
  'tr.snapchat.com/'
  'tr6.snapchat.com/'
  'universal.iperceptions.com'
  'video.tv.adobe.com'
  'vimeo.com'
  'www.facebook.com'
  'www.youtube.com'
  's.company-target.com'
  '10.129.79.105:15871'
  '10.13.1.61:15871'
  '10.164.60.151:15871'
  '172.16.123.71:15871'
  '25.19.243.204:15871'
  'accessdenied.pnc.com'
  '172.24.9.75:15871'
  'gateway.zscaler.net'
  'gateway.zscalertwo.net'
  'gateway.zscloud.net'
  'pixel.everesttech.net'
  'safe.menlosecurity.com'
  'td.doubleclick.net'
  'trendlavida.com'
  'zswpmanager.wip.mmc.com'
  ';'',
];

const imgSrc = [
  '\'self\''
  'about:'
  'blob:'
  'data:'
  '*.clarity.ms'
  '*.services.adobe.com'
  'alb.reddit.com/rp.gif'
  'analytics.twitter.com/'
  'bat.bing.com/action/'
  'c.clicktale.net/'
  'cc-prod.scene7.com/'
  'cdn.cookielaw.org'
  'cm.everesttech.net/cm/'
  'cx.atdmt.com'
  'dpm.demdex.net'
  'googleads.g.doubleclick.net/pagead/'
  'googleads.g.doubleclick.net/pagead/viewthroughconversion/'
  'id.rlcdn.com/'
  'match.prod.bidr.io/cookie-sync/'
  'match.prod.bird.io/cookie-sync/'
  'p.adsymptotic.com/d/px/'
  'pt.ispot.tv/'
  'px.ads.linkedin.com'
  'segments.company-target.com'
  'so.rlcdn.com/'
  't.co/i/'
  'www.adobe.com'
  'www.facebook.com/'
  'www.facebook.com/tr/'
  'www.google.ch/pagead/'
  'www.google.co.in/pagead/'
  'www.google.co.jp/pagead/'
  'www.google.com.au/pagead/'
  'www.google.com/pagead/'
  'www.google.ie/pagead/1p-user-list/'
  'www.googletagmanager.com/'
  'www.linkedin.com'
  'main--dc--adobecom.hlx.page'
  'main--milo--adobecom.hlx.page'
  'a5.behance.net'
  'www.googletagmanager.com'
  'milo.adobe.com'
  'p.typekit.net'
  's.tgm.yahoo-net.jp'
  'l.clicktale.net'
  'www.google.ca'
  'www.google.co.kr'
  'www.google.co.uk'
  'www.google.co.za'
  'www.google.com'
  'www.google.com.mx'
  'www.google.com.sa'
  'www.google.com.tr'
  'www.google.com.tw'
  'www.google.de'
  'www.google.fr'
  'www.google.it'
  'adservice.google.com'
  'analytics.tiktok.com'
  'analytics.twitter.com'
  'c.clicktale.net'
  'googleads.g.doubleclick.net'
  'id.rlcdn.com'
  'mir-s3-cdn-cf.behance.net'
  't.co'
  'translate.google.com'
  'www.facebook.com'
  'www.google.ae'
  'www.google.al'
  'www.google.at'
  'www.google.az'
  'www.google.ba'
  'www.google.be'
  'www.google.bg'
  'www.google.bi'
  'www.google.bs'
  'www.google.bt'
  'www.google.by'
  'www.google.cd'
  'www.google.ci'
  'www.google.cl'
  'www.google.cm'
  'www.google.co.ao'
  'www.google.co.bw'
  'www.google.co.cr'
  'www.google.co.id'
  'www.google.co.il'
  'www.google.co.ke'
  'www.google.co.ls'
  'www.google.co.ma'
  'www.google.co.mz'
  'www.google.co.nz'
  'www.google.co.th'
  'www.google.co.tz'
  'www.google.co.ug'
  'www.google.co.uz'
  'www.google.co.ve'
  'www.google.co.zm'
  'www.google.co.zw'
  'www.google.com.af'
  'www.google.com.ar'
  'www.google.com.bd'
  'www.google.com.bh'
  'www.google.com.bo'
  'www.google.com.br'
  ';'',
];

const manifestSrc = [
  '\'self\'',
  ';',
];

const scriptSrc = [
  '\'self\'',
  '\'unsafe-eval\'',
  '*.adobe.com',
  '*.clarity.ms',
  'accounts.google.com/gsi/client',
  'ade0164.d41.co/sync/',
  'adobe.demdex.net/',
  'adobe.tt.omtrdc.net',
  'adobedc.demdex.net/',
  'adobeioruntime.net/api/',
  'analytics.tiktok.com/',
  'analytics.twitter.com',
  'api.company-target.com/api/v2/',
  'api.demandbase.com/api/',
  'api.iperceptions.com',
  'assets.adobedtm.com',
  'bat.bing.com',
  'bid.g.doubleclick.net',
  'cdn.cookielaw.org/scripttemplates/',
  'cdn.pdst.fm',
  'cdnssl.clicktale.net/',
  'cm.everesttech.net',
  'connect.facebook.net',
  'cx.atdmt.com',
  'dpm.demdex.net',
  'ecf.d41.co/',
  'geolocation.onetrust.com',
  'googleads.g.doubleclick.net',
  'googleads.g.doubleclick.net/pagead/viewthroughconversion/',
  'lasteventf-tm.everesttech.net',
  'match.prod.bidr.io/cookie-sync/',
  'munchkin.marketo.net/',
  'p.adsymptotic.com/d/px',
  'pixel.everesttech.net/rlsa/',
  'px.ads.linkedin.com',
  'rs.gwallet.com',
  's.go-mpulse.net/',
  's2.go-mpulse.net',
  'sc-static.net/',
  'scripts.demandbase.com',
  'sd.iperceptions.com',
  'segments.company-target.com',
  'servedby.flashtalking.com',
  'snap.licdn.com',
  'so.rlcdn.com/',
  'static.ads-twitter.com',
  't.co/i',
  'tag.clrstm.com',
  'tr.snapchat.com/',
  'universal.iperceptions.com',
  'use.typekit.net',
  'www.everestjs.net/static/le/',
  'www.facebook.com',
  'www.google.com',
  'www.googleadservices.com/pagead/',
  'www.googletagmanager.com/',
  'www.linkedin.com/px',
  'www.redditstatic.com/ads/pixel.js',
  'cdn.megadata.co.kr',
  'tk.mediacategory.com',
  't1.daumcdn.net',
  'bc.ad.daum.net',
  'cdn.taboola.com',
  'pips.taboola.com',
  'trc.taboola.com',
  'js.adsrvr.org',
  'main--milo--adobecom.hlx.page',
  'tag.demandbase.com',
  '*.typekit.net',
  'zn3n5vyia1vy8b4ly-adobe.siteintercept.qualtrics.com/',
  ';',
];

const styleSrc = [
  '\'self\'',
  '\'unsafe-inline\'',
  '*.adobe.com',
  'accounts.google.com/gsi/style',
  'adobeccstatic.com',
  'use.typekit.net',
  'main--milo--adobecom.hlx.page',
  'p.typekit.net',
  ';',
];

const workerSrc = [
  '\'self\'',
  'blob:',
  'cdnssl.clicktale.net',
  'www.adobe.com/',
  ';',
];

export default { connectSrc, defaultSrc, fontSrc, formAction, frameSrc, imgSrc, manifestSrc, scriptSrc, styleSrc, workerSrc};
