name: Lint
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - stage
      - main
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - uses: reviewdog/action-eslint@v1
      with:
        filter_mode: file
        fail_on_error: true
